In [26]:
import numpy as np

In [39]:
arr = np.array ([20, 40, 80, 100, 120])
arr.tolist()

[20, 40, 80, 100, 120]

In [50]:
n_array = np.array([[20, 40, 30],[1, 12, 66]])
trace = np.trace(n_array)
print(trace)

32


In [62]:
x = np.array([[5,7,3],[2,6,5]])

print( x[x>5])
print( np.nonzero(x > 5))

[7 6]
(array([0, 1]), array([1, 1]))


In [64]:
a = np.array([5,4,11])
b = np.array([2,6,9])
c = a+b
print("c=",c)

c= [ 7 10 20]


In [72]:
a = np.random.rand(3, 4)
b = np.random.rand(3, 4)
c = a - a.mean(axis=1, keepdims=True)
d = b - b.mean(axis=1, keepdims=True)
print(c)
print (d)

[[ 0.32523016  0.30384812 -0.16625759 -0.46282069]
 [ 0.14232621  0.03281256 -0.33276277  0.157624  ]
 [-0.16462572 -0.17343634  0.41227106 -0.074209  ]]
[[-0.16499306  0.25414484 -0.04525944 -0.04389234]
 [ 0.34673611 -0.37988413 -0.17819419  0.2113422 ]
 [ 0.03435455 -0.25795935  0.46829656 -0.24469176]]
